name: Upload Nightly
description: A GitHub Action to upload artifacts nightly
permissions:
  actions: read
  contents: read
  metadata: read
author: "Scientific-Python"
version: "0.1.0"

inputs:
  artifacts_path:
    description: 'Path to the artifacts directory where wheels to upload are present'
    required: true
  anaconda_nightly_upload_token:
    description: 'Token to upload to scientific python org'
    required: true
  anaconda_nightly_upload_url:
    description: 'URL to upload to scientific python org'
    required: false
    default: scientific-python-nightly-wheels
  anaconda_nightly_upload_labels:
    description: 'Labels assigned to the uploaded artifacts'
    required: false
    default: main

runs:
  using: 'docker'
  image: 'Dockerfile'
