name: Upload Nightly
description: A GitHub Action to upload artifacts nightly
permissions:
  actions: read
  contents: read
  metadata: read
author: "Scientific-Python"
version: "0.6.1"

inputs:
  artifacts_path:
    description: 'Path to the artifacts directory where wheels to upload are present'
    required: true
  anaconda_nightly_upload_token:
    description: 'Token to upload to scientific python org'
    required: true
  anaconda_nightly_upload_organization:
    description: 'Organisation name to upload the wheels to'
    required: false
    default: scientific-python-nightly-wheels
  anaconda_nightly_upload_labels:
    description: 'List of labels assigned to the uploaded artifacts'
    required: false
    default: main

runs:
  using: "composite"
  steps:
    - name: Set up pixi
      uses: prefix-dev/setup-pixi@92815284c57faa15cd896c4d5cfb2d59f32dc43d  # v0.8.3
      with:
        locked: true
        cache: true
        cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        # Avoid post cleanup errors if action run multiple times
        post-cleanup: false
        # Action consumers should load the lock file from the action repo
        manifest-path: ${{ github.action_path }}/pixi.toml

    - name: Upload wheels
      shell: bash
      env:
        INPUT_ARTIFACTS_PATH: ${{ inputs.artifacts_path }}
        INPUT_ANACONDA_NIGHTLY_UPLOAD_ORGANIZATION: ${{ inputs.anaconda_nightly_upload_organization }}
        INPUT_ANACONDA_NIGHTLY_UPLOAD_TOKEN: ${{ inputs.anaconda_nightly_upload_token }}
        INPUT_ANACONDA_NIGHTLY_UPLOAD_LABELS: ${{ inputs.anaconda_nightly_upload_labels }}
      run: |
        pixi run --manifest-path ${{ github.action_path }}/pixi.toml ${{ github.action_path }}/upload_wheels.sh
