[workspace]
authors = ["Scientific Python"]
channels = ["conda-forge"]
description = "Environment for the scientific-python/upload-nightly-action GitHub action"
name = "upload-nightly-action"
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64"]
version = "0.6.4"
requires-pixi = ">=0.67.0"
# month window to find security issues
exclude-newer = "30d"

[tasks]

[dependencies]
anaconda-client = "==1.14.1"
