name: Scientific Python / Remove Old Wheels
description: A GitHub Action to remove old wheels
permissions:
  actions: read
  contents: read
  metadata: read
author: "Scientific-Python"
# TODO: have to think about versioning; whether to version separately, or
# for it to be in sync with the version for the upload action
version: "0.1.0" # should be kept in sync with the version in remove-wheels/pixi.toml

inputs:
  n_latest_uploads:
    description: 'The number of previous wheel uploads to keep'
    required: false
    default: '5'
  anaconda_nightly_upload_organization:
    description: 'Anaconda Cloud organisation name to remove the wheels from'
    required: false
    default: scientific-python-nightly-wheels
  anaconda_nightly_token:
    description: 'Anaconda Cloud API token to authenticate with'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up pixi
      uses: prefix-dev/setup-pixi@ba3bb36eb2066252b2363392b7739741bb777659  # v0.8.1
      with:
        locked: true
        cache: true
        cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        # Avoid post cleanup errors if action run multiple times
        post-cleanup: false
        # Action consumers should load the lock file from the action repo
        manifest-path: ${{ github.action_path }}/pixi.toml

    - name: Remove old wheels
      shell: bash
      env:
        INPUT_N_LATEST_UPLOADS: ${{ inputs.n_latest_uploads }}
        INPUT_ANACONDA_USER: ${{ inputs.anaconda_user }}
        INPUT_ANACONDA_TOKEN: ${{ inputs.anaconda_token }}
      run: |
        pixi run --manifest-path ${{ github.action_path }}/remove-wheels/pixi.toml ${{ github.action_path }}/remove_wheels.sh
