[workspace]
authors = ["Scientific Python"]
channels = ["conda-forge"]
description = "Environment for the scientific-python/upload-nightly-action/remove-wheels GitHub action"
name = "remove-wheels"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"
requires-pixi = ">=0.67.0"
exclude-newer = "30d"

[tasks]

[dependencies]
anaconda-client = "==1.14.1"
jq = "==1.7.1"
