name: Remove old wheels

on:
  # Run daily at 1:23 UTC
  schedule:
    - cron: '23 1 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  N_LATEST_UPLOADS: 5
  ANACONDA_USER: "scientific-python-nightly-wheels"

jobs:
  get-pkgs:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'scientific-python'
    # Set required workflow secrets in the environment for additional security
    # https://github.com/scientific-python/upload-nightly-action/settings/environments
    environment:
      name: remove-old-wheels

    outputs:
      pkgnames: ${{ steps.set-outputs.outputs.pkgnames }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e  # v0.10.2
        with:
          locked: true

      - name: Generate list of package names
        id: set-outputs
        shell: pixi run --manifest-path pixi.toml bash -e {0}
        run: |
          pkgs_json=$(anaconda show "${ANACONDA_USER}" 2>&1 | grep "${ANACONDA_USER}/" | \
              awk '{print $1}' | \
              sed 's|.*/||g' | \
              grep -vf packages-ignore-from-cleanup.txt | \
              python -c 'import sys, json; print(json.dumps([line.strip() for line in sys.stdin if line.strip()]))')
          echo "pkgnames=${pkgs_json}" >> "$GITHUB_OUTPUT"

  remove:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'scientific-python'
    # Set required workflow secrets in the environment for additional security
    # https://github.com/scientific-python/upload-nightly-action/settings/environments
    environment:
      name: remove-old-wheels

    needs: [get-pkgs]

    strategy:
      matrix:
        pkgname: ${{fromJSON(needs.get-pkgs.outputs.pkgnames)}}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Remove old wheels
        uses: ./remove-wheels
        with:
          n_latest_uploads_to_keep: ${{ env.N_LATEST_UPLOADS }}
          anaconda_nightly_upload_organization: ${{ env.ANACONDA_USER }}
          anaconda_nightly_token: ${{ secrets.ANACONDA_TOKEN }}
          package_name: ${{ matrix.pkgname }}

  report-failure:
    needs: [remove]
    if: failure() && github.event_name == 'schedule'
    permissions:
      issues: write
    uses: ./.github/workflows/report-failure.yml
    with:
      title: 'The old wheel cleanup is failing'
