name: Remove old wheels

on:
  # Run daily at 1:23 UTC
  schedule:
    - cron: '23 1 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  N_LATEST_UPLOADS: 5
  ANACONDA_USER: "scientific-python-nightly-wheels"

jobs:
  get-pkgs:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'scientific-python'
    # Set required workflow secrets in the environment for additional security
    # https://github.com/scientific-python/upload-nightly-action/settings/environments
    environment:
      name: remove-old-wheels

    outputs:
      pkgnames: ${{ steps.set-outputs.outputs.pkgnames }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
        with:
          locked: true
          environments: remove

      - name: Generate list of package names
        id: set-outputs
        shell: pixi run --manifest-path pixi.toml --environment remove bash -e {0}
        run: |
          pkgs_json=$(anaconda show "${ANACONDA_USER}" 2>&1 | grep "${ANACONDA_USER}/" | \
              awk '{print $1}' | \
              sed 's|.*/||g' | \
              grep -vf packages-ignore-from-cleanup.txt | \
              jq -Rn '[inputs]')
          echo "pkgnames=${pkgs_json}" >> "$GITHUB_OUTPUT"

  remove:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'scientific-python'
    # Set required workflow secrets in the environment for additional security
    # https://github.com/scientific-python/upload-nightly-action/settings/environments
    environment:
      name: remove-old-wheels

    needs: [get-pkgs]

    strategy:
      matrix:
        pkgname: ${{fromJSON(needs.get-pkgs.outputs.pkgnames)}}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Remove old wheels
        uses: ./remove-wheels
        with:
          n_latest_uploads_to_keep: ${{ env.N_LATEST_UPLOADS }}
          anaconda_nightly_upload_organization: ${{ env.ANACONDA_USER }}
          anaconda_nightly_token: ${{ secrets.ANACONDA_TOKEN }}
          package_name: ${{ matrix.pkgname }}
